#install.packages("blogdown")
library(blogdown)
#if (!requireNamespace("remotes")) install.packages("remotes")
 #remotes::install_github("rstudio/blogdown")
#new_site(theme = "wowchemy/starter-academic")
blogdown::serve_site() 
blogdown::check_gitignore()
blogdown::check_content()

library(bib2academic)
library(bibtex)
bib2acad("citations.bib", copybib = TRUE, abstract = TRUE, overwrite = TRUE)
